graph LR;
    AP_Chem;
    AP_Phy_1-->AP_Phy_2-->AP_Phy_C_E&M-->AP_Phy_C_Mech;
    AP_Bio;
    AP_Env;
    AP_Pre-Calc
    AP_calc_AB-->AP_calc_BC-->Calc_3
    AP_Stat
    Pre-AP_ELA_2
    AP_Lang-->AP_Lit
    A_PUSH
    AP_World
    AP_HUG
    AP_Micro-->AP_Macro
    AP_Seminar-->AP_Research
    AP_Comp_Princ-->AP_Comp_A
    AP_Music_Theory
    Spanish_1-->Spanish_2-->Spanish_3-->Spanish_4-->AP_Spanish_Lit-->AP_Spanish_Lang
