graph LR;
    10_SUM-->10_FALL-->10_SPRING-->11_SUM-->11_FALL-->11_SPRING-->12_SUM-->12_FALL-->12_SPRING
    10_SUM-->Chem_Hon-->10_FALL
    10_SUM-->Hope-->10_FALL
    10_SUM-->Comp1-->10_FALL
    Spanish_2-->Spanish_3-->Spanish_4-->AP_Spanish_Lit-->AP_Spanish_Lang
    AP_Phy_1-->AP_Phy_2-->AP_Phy_C_E&M-->AP_Phy_C_Mech;
    AP_calc_AB-->AP_calc_BC-->Calc_3
    AP_Lang-->AP_Lit
    AP_Micro-->AP_Macro
    AP_Seminar-->AP_Research
    AP_Comp_Princ-->AP_Comp_A
    AP_Bio;
    AP_Chem;
    AP_Env;
    AP_Pre-Calc
    AP_Stat
    Pre-AP_ELA_2
    A_PUSH
    AP_World
    AP_HUG
    AP_Music_Theory
